name: cjm-demucs-v4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pytorch>=2.0
  - pytorch-cuda>=12.0
  - ffmpeg>=4.2
  - pip
  - pip:
    - einops
    - julius>=0.2.3
    - lameenc>=1.2
    - openunmix
    - pyyaml
    - torchcodec
    - tqdm
